### ISSUE TITLE
Suggestion: levels

### ISSUE THREAD

**Issue by drdavel2** [renoth/factorio-factory-levels#1]
Hi there and thank you for great mod with fresh idea!
Please say, is it real to give buildings just permanent bonuses to speed/low-power-consuption/productivity instead of changing tier of building? If it's real please code that feature and please do checkboxes in setup menu to able to disable upgrade tier level feature. Hope you'll understand me. Best regards!

**Comment by InCo2832** [comment]
Very cool! This is exactly what I have always wanted in Factorio. But, if possible, please make a checkbox to turn off the color change of assemblers)

**Comment by renoth** [comment]
Unfortunately the Factiorio Modding API does not allow changing of Building or Item properties at runtime. All properties have to be assigned to buildings that replace each other ingame.
There are also no moddable modifiers like factory speed.
The only way to achieve this at the moment is by replacing buildings or recipes.
@InCo2832 The color change is subject to change and i will make it less obvious, it was for testing purposes at the moment

**Comment by renoth** [comment]
changed the colors in 0.1.2
