### ISSUE TITLE
UPS drop

### ISSUE THREAD

**Issue by skRIPpatch** [renoth/factorio-factory-levels#14]
![Снимок экрана 2022-07-28 153753](https://user-images.githubusercontent.com/40587371/181462718-dfb72eac-b558-4f95-a3bf-f2ee39670a65.png)
For some reason enabling this mod and the [Eradicator's Belt Planner](https://mods.factorio.com/mod/eradicators-belt-planner) results in UPS drop. Also, when turned on belt planner, time usage increases. 
![Снимок экрана 2022-07-28 153854](https://user-images.githubusercontent.com/40587371/181462695-7975f0f7-b0f1-4648-a537-f10dad49075d.png)

**Comment by skRIPpatch** [comment]
![image](https://user-images.githubusercontent.com/40587371/182201992-c2579655-a9b8-4ba3-b439-3550a8b8f3e0.png)
Yeah, thats works perfectly

**Comment by unhott** [comment]
Absolutely! I'm glad it was able to make it in, and hopefully this helps people enjoy the mod more!
