### ISSUE TITLE
New game

### ISSUE THREAD

**Issue by InCo2832** [renoth/factorio-factory-levels#15]
![изображение](https://user-images.githubusercontent.com/109705653/182174468-084ab88c-56d5-4b61-8376-7c88ea6f0257.png)
On start of a New Game(1.1.61 Steam Stable) First furnace become a 25 lvl, is it a bug or a feature?))
(No other mods)

**Comment by renoth** [comment]
This is testcode not being deleted

**Comment by renoth** [comment]
Will be fixed in 0.4.1

**Comment by renoth** [comment]
fixed in 0.4.1

**Comment by renoth** [comment]
Thanks for reporting!
