### ISSUE TITLE
Suggestion: toggle to do it per item instead of global level

### ISSUE THREAD

**Issue by skelgaard** [renoth/factorio-factory-levels#16]

**Comment by renoth** [comment]
I am sorry i do not understand this suggestion. Can you elaborate?

**Comment by skelgaard** [comment]
that the level is not global, but for iron plates, cobber plates,.....

so that iron plates can be at level 25 but cobber plates are only on level 5 and wire is level 99 and so on

**Comment by renoth** [comment]
The level of assemblers and furnaces is individual for every entitiy. The level is determined by the produced count of the assembler/furnace. There is no global level.
