### ISSUE TITLE
Productivty from Factories gone?

### ISSUE THREAD

**Issue by Chaoschaot232** [renoth/factorio-factory-levels#24]
In https://github.com/renoth/factorio-factory-levels/commit/18b39366b054204eb7aee98611b51e481996e94d I have noticed that productivity for assambling machines where removed and I dislike this, if this is intended instead of a bug.

Please re-enable this beavior, otherwise I must fallback to an older version or replace the new code with the old ones.

Furnaces are working fine but Assamblers are not longer having productivity bonuses compared to there level whith which I disagree.

**Comment by JohnyDL** [comment]
Um a quick code dive (and from running the code in-game) the productivity in assemblers does not appear to have been removed... the code has just been refactored so it's being done by a function with a different name that works on centrifuges and assemblers and furnaces and has the option for even more mod support in the future.

**Comment by Chaoschaot232** [comment]
@JohnyDL I know, since I have also looked this code up but why is it gone for my leveled factories?

Here it should definitly have the Prod-Bar but it's gone:
![image](https://user-images.githubusercontent.com/1703441/185173881-66a8b84a-ea01-4750-b658-cf9220ed74f7.png)

Here ist should state the Prod-Factor but it's gone too:
![image](https://user-images.githubusercontent.com/1703441/185174084-92a69879-1b78-4796-980d-4ec304a7cee5.png)

So smth. went wrong with the migrationsscript and the update.

**Comment by JohnyDL** [comment]
it's level 16, I think but I'm not certain that productivity is only done in whole numbers of % on the C side of the code (nothing to do with the mod) so level 16 would give a productivity bonus of +0.4% which would round down to 0.

**Comment by Chaoschaot232** [comment]
> it's level 16, I think but I'm not certain that productivity is only done in whole numbers of % on the C side of the code (nothing to do with the mod) so level 16 would give a productivity bonus of +0.4% which would round down to 0.

That's not correct because in the previous version there was productivity active at this level and it is still active for furnaces:

2% of Productivity applied:
![image](https://user-images.githubusercontent.com/1703441/185336165-cf72f9cd-e882-49fe-ad33-161700c76540.png)

Productivity Bar:
![image](https://user-images.githubusercontent.com/1703441/185336307-13381152-d1fd-48ad-a179-61e3954fcc16.png)

And this was also there for the assemblers.

**Comment by CaitSith2** [comment]
Now just waiting for @renoth  to merge the PR. once back from vacation (or maybe sooner)
