### ISSUE TITLE
Items lost in manufacturing

### ISSUE THREAD

**Issue by pvalincius** [renoth/factorio-factory-levels#25]
I noticed that when centrafuge upgrades all manufactured items are lost. Dont know if it's true for the rest factories.

**Comment by K-DaK** [comment]
Chemical plant ate a whole stack of coal and all plastic that was sitting in the output when it leveled up.

**Comment by TheoMarque** [comment]
Items that was stored in machine to be used for product, gone if factory level up. Modules were saved (as intended) but ingredients gone. For cheap resources - is not a problem but is a very high problem with expensive products. 

For example Centrifuge with Kovarex -> all U235 was cleared after factory was leveled.
