### ISSUE TITLE
Pipette tool doesn't work for leveled entities

### ISSUE THREAD

**Issue by aarons** [renoth/factorio-factory-levels#3]
Fantastic idea for a mod! I'm really enjoying the level up aspect of the assemblers. 

One feature request (or bug I suppose) would be for the pipette (default 'Q') to work for assemblers that have leveled. Ideally after using the pipette tool I would have a base level assembler selected for placement. 

[Hero Turrets](https://github.com/pixelwhipped/ModMash/tree/master/ModMash/HeroTurrets) has a solution for leveled turrets, where ghosts and the pipette tool give the unleveled variant.

**Comment by renoth** [comment]
the solution is rather easy: https://wiki.factorio.com/Prototype/Entity#placeable_by
Thanks for reporting

**Comment by aarons** [comment]
Wow, thanks for the fast update!! Really digging your mod. Cheers!
