### ISSUE TITLE
bobs and angels playthrough

### ISSUE THREAD

**Issue by Panterh3art** [renoth/factorio-factory-levels#33]
hello i am playing bobs and angels seablock

and with my power i have an issue
it seems when certain machines hit max level they change to a whole different machine
for example an liquefier gets changed to an ore crusher

**Comment by IamJamesP** [comment]
I am also having the exact same issue with the Liquifier.
Took me a while to work out why all of them were replaced with Ore Crushers...
The Ore Crushers level up completely fine however, just seems like that machine so far for me

**Comment by Panterh3art** [comment]
Yeah it seems like that but with the latest update of 0.6.8 of this mod it says in the changelog that the machines dont auto promote to a mk2 machine but it still does that

**Comment by IamJamesP** [comment]
Yep, 
Auto-levels up for me too.
I missed that part of the changelog, there doesn't seem to be anything within game settings for enabling/disabling that either

**Comment by Panterh3art** [comment]
["liquifier"] = {
		name = "liquifier",
		level_name = "liquifier-level-",
		max_level = 25,
		next_machine = "ore-crusher"
	},
	["liquifier-2"] = {
		name = "liquifier-2",
		level_name = "liquifier-2-level-",
		max_level = 25,
		next_machine = "ore-crusher-2"
	},
	["liquifier-3"] = {
		name = "liquifier-3",
		level_name = "liquifier-3-level-",
		max_level = 50,
		next_machine = "ore-crusher-3"
	},
	["liquifier-4"] = {
		name = "liquifier-4",
		level_name = "liquifier-4-level-",
		max_level = 100
	}, 
found the issue it's in the control.loua 

["liquifier"] = {
		name = "liquifier",
		level_name = "liquifier-level-",
		max_level = 25,
		next_machine = "liquifier-2"
	},
	["liquifier-2"] = {
		name = "liquifier-2",
		level_name = "liquifier-2-level-",
		max_level = 25,
		next_machine = "liquifier-3"
	},
	["liquifier-3"] = {
		name = "liquifier-3",
		level_name = "liquifier-3-level-",
		max_level = 50,
		next_machine = "liquifier-4"
	},
	["liquifier-4"] = {
		name = "liquifier-4",
		level_name = "liquifier-4-level-",
		max_level = 100
	},

This should be the fix

**Comment by renoth** [comment]
Thank you very much, released in 0.6.9
