### ISSUE TITLE
Leveled Assemblers loosing recipies

### ISSUE THREAD

**Issue by Chaoschaot232** [renoth/factorio-factory-levels#42]
Not sure if you could connect this with #20 but when an Assembler levels up it looses access to certain recipes.
I could think of missing dependencies here but unsure about this.

Would be nice if a look into this could be taken.

**Comment by renoth** [comment]
What mods do you use?

**Comment by Chaoschaot232** [comment]
Here is my mod-list.json file, be aware that I must have had to change a few mods on my own to get rid of some errors like 248k mod.
[mod-list.json](https://github.com/renoth/factorio-factory-levels/files/13539582/mod-list.json)

**Comment by renoth** [comment]
Thats a lot of mods, all i can say is that it works with this mod standalone, you could do a binary search in disabling the mods until you find the mod responsible and then ask them to fix it.
