### ISSUE TITLE
error copper wire

### ISSUE THREAD

**Issue by Keiichi88** [renoth/factorio-factory-levels#48]
error copper wire, receipt copper wire first assembler. Error after insert copper plate
![20241021211300_1](https://github.com/user-attachments/assets/4064299c-a9d2-4160-bde8-251cf385ab95)

**Comment by Tenderroast** [comment]
Error appears to happen on many different things. I think it has to do with the changes made to inserters in Space Age.

**Comment by renoth** [comment]
did you load a pre 2.0 savegame?

**Comment by renoth** [comment]
Duplicates #49
