### ISSUE TITLE
space age game crash

### ISSUE THREAD

**Issue by Tenderroast** [renoth/factorio-factory-levels#49]
With Space Age, I just had a game crashing error. 

The mod Factory Levels (0.7.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-levels::on_nth_tick(6)
Invalid ItemID: expected LuaItemPrototype, LuaItemStack, LuaItem or string.
stack traceback:
	[C]: in function 'insert'
	__factory-levels__/control.lua:347: in function 'insert_inventory_contents'
	__factory-levels__/control.lua:414: in function 'upgrade_factory'
	__factory-levels__/control.lua:438: in function 'replace_machines'
	__factory-levels__/control.lua:487: in function <__factory-levels__/control.lua:467>

**Comment by hedemen** [comment]
i have this one as well and confirm it is happening as a standalone mod as well

**Comment by Tenderroast** [comment]
going to have to disable this awesome mod for the time being until it gets fixed

**Comment by renoth** [comment]
Which mods are you using? Space Age? Only this mod?

**Comment by renoth** [comment]
Did you start a completely new game or did you load a pre 2.0 savegame?

**Comment by renoth** [comment]
Yes i see the problem now, the leveled assemblers cannot make copper wire or transport belts and the game crashes when upgrading from normal to level 1 assembler

**Comment by renoth** [comment]
Should be fixed in 0.7.1
