### ISSUE TITLE
Error when centrifuge is running

### ISSUE THREAD

**Issue by kolaster** [renoth/factorio-factory-levels#51]
![image](https://github.com/user-attachments/assets/89251536-b1f0-452d-bb3d-014604e27890)
I can install it, but when it finishes the work cycle, an error occurs in the screenshot

**Comment by renoth** [comment]
should be fixed in 0.7.2. Please test

**Comment by Pr0seid0n** [comment]
i had this issue after updateing
![Bild_2024-10-22_143840950](https://github.com/user-attachments/assets/6ac19d86-9fb5-46ed-a662-e64bbb955e73)
