### ISSUE TITLE
HI ! I NEED YOUR HELP

### ISSUE THREAD

**Issue by garden0566666** [renoth/factorio-factory-levels#53]
I really like your mod

However, an error suddenly occurred, so I captured the contents and attached it.

I think your factory level up mode is really innovative

I sincerely hope your mod is fixed as soon as possible. Thank you.

![asdasd](https://github.com/user-attachments/assets/39cc1825-b7f7-43e1-85ea-8c09f93c138c)

**Comment by renoth** [comment]
Do you use any other mods? When does this error occur?
