### ISSUE TITLE
Unable to use upgrade plan after disabling quality in mod settings

### ISSUE THREAD

**Issue by lukasindy** [renoth/factorio-factory-levels#55]
If I deactivate Quality in the mod settings, I can no longer use the upgrade plan for assembly machines and furnaces.

**Comment by renoth** [comment]
I do not understand, what do you mean by upgrade plan?

**Comment by StratsScorpio** [comment]
I've not deactivated Quality, but can also not use the upgrade plan.

I can only sellect in the "from" field the base module, but in the "to" field I've all possible levels. Upgrading does not work. The level factories are not associated with the base module. What I need, like before: module1 -> module2 independent of level .
![From](https://github.com/user-attachments/assets/93021166-11ef-43d4-b2cf-d0b1b1fbda20)
![To](https://github.com/user-attachments/assets/0b8b3756-65ac-40da-8079-f40052467596)

**Comment by renoth** [comment]
Should be fixed in 0.7.7

**Comment by StratsScorpio** [comment]
Yes, it does. Thank you.

The upgrade plan is very confusing due to the many levels.
Is there a simplification that allows you to tell the bots, "No matter what level, upgrade"?

**Comment by renoth** [comment]
At the moment i dont see a way with the modding API
