### ISSUE TITLE
CRASH !

### ISSUE THREAD

**Issue by zodanhgame** [renoth/factorio-factory-levels#57]
Help me :( 
<img width="353" alt="Screenshot 2024-10-23 170153" src="https://github.com/user-attachments/assets/9e6e7a3f-b4bf-4183-8037-800d79a6fb77">
Mod used :
<img width="490" alt="3" src="https://github.com/user-attachments/assets/13c1bc65-ae5e-415a-9a76-8d88f65b9adb">
<img width="482" alt="2" src="https://github.com/user-attachments/assets/f1584d09-32da-4e69-b63e-4aaefe844421">

**Comment by DarkTitanZagalt** [comment]
Same here error here.
![error](https://github.com/user-attachments/assets/3f50fead-a9ca-4695-8a2d-69eeb3946358)

Not sure what caused it as I had a bunch of stuff going on at the same time. I was about an hour into a play session. Here's my mod list:
![mods](https://github.com/user-attachments/assets/ca45d8c4-6460-403e-bf66-7bdb1ae14be1)
