### ISSUE TITLE
Module Slots not updating correctly with Levelups

### ISSUE THREAD

**Issue by GitFlyingGecko** [renoth/factorio-factory-levels#58]
Seems like only base module slots are used. Bonus modules slots are not added, when machines reach the threshold levels.

No other mods modifying the machines used. Tested with furnaces, assembler 1-3, oil refinery and chemical plant.
None of them added a bonus module slot on reaching threshold Levels for bonus modules. Rebuilding the machines to force a recalculation of bonus values did nothing. All other properties (such speed, polution, qualitiy...) are updated correctly.

Screenshots of some examples attached.

![grafik](https://github.com/user-attachments/assets/384aa7c8-4951-4cec-b9bc-aeb6b3157276)
![grafik](https://github.com/user-attachments/assets/224a85a2-750f-498e-9057-8557519fba25)
![grafik](https://github.com/user-attachments/assets/0cfa5e20-871a-40da-ae56-a4c20657f7a5)
![grafik](https://github.com/user-attachments/assets/db329263-b495-4e18-993b-8632562a8742)

**Comment by renoth** [comment]
pleasee test with the latest version 0.7.6

**Comment by GitFlyingGecko** [comment]
Fixed. Thank you for your fast response!
