### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Valkaziim** [renoth/factorio-factory-levels#59]
Recieving this error, my only guess is it is when a building is upgrading, and clicking the remove mod option to uninstall the mod crashes aswell.
![427520_13](https://github.com/user-attachments/assets/2332de9b-d44c-43d4-b8e0-9c410b7e8dbc)

**Comment by Valkaziim** [comment]
This error when trying to use the remove option
![427520_14](https://github.com/user-attachments/assets/5b6c85ca-bfee-464f-be5d-e67da97a8bbd)

**Comment by renoth** [comment]
Duplicate of #61
