### ISSUE TITLE
Crash when activating mod on existing save

### ISSUE THREAD

**Issue by ololduck** [renoth/factorio-factory-levels#61]
Hi, I wanted to have a look at this mod, because i like the idea of self-improving hardware. However, when loading the mod, the following error occurred:

![image](https://github.com/user-attachments/assets/7324ff3e-e82e-4459-b3f1-53d5e961d018)

Here's the text version for convenience:

```
The mod Factory Levels (0.7.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-levels::on_runtime_mod_setting_changed (ID 63)
Invalid ItemID: expected LuaItemPrototype, LuaItemStack, LuaItem or string.
stack traceback:
	[C]: in function 'insert'
	__factory-levels__/control.lua:347: in function 'insert_inventory_contents'
	__factory-levels__/control.lua:415: in function 'upgrade_factory'
	__factory-levels__/control.lua:439: in function 'replace_machines'
	__factory-levels__/control.lua:31: in function 'get_built_machines'
	__factory-levels__/control.lua:553: in function <__factory-levels__/control.lua:550>
```

It is *not* a blocking issue, as my old savegame, without the mod active, loads fine.

# Context of the crash

I've looked at the other opened issues, and although they present a similar issue, in my error message, the line numbers are different.

- I have Space Age & Quality active
- The savegame is already quite advanced and most machines have produced enough items to trigger level evolution
- Some machines have quality-enabled inputs & outputs
- Some machines have quality themselves
- Some machines have quality modules inside them
- Some machines have quality-enabled quality|productivity modules inside them
- Some inserters have quality filters

## How to reproduce

Loading the game with the Factory Levels mod enabled. The popup appears immediately after load.
I'm not sure, but maybe i can send you my save file(s)?

I tried to reproduce it on a new save, but whatever i did, i could not reproduce it. I may be missing something.

**Comment by renoth** [comment]
Please try 0.7.7

**Comment by ololduck** [comment]
Well, it actually works!
Well done and thank you!

**Comment by IG2WTC** [comment]
0.7.7 seems to have also fixed it for me!
Thank you so much!
