### ISSUE TITLE
Recipe Quality is not persisted between assembler upgrades

### ISSUE THREAD

**Issue by ololduck** [renoth/factorio-factory-levels#62]
Hi, sorry for the second issue.

After some investigation, I found out that recipe quality is not persisted when an assembler is upgraded to the next level.

# How to reproduce

Here's me selecting a "Uncommon" green circuit recipe:
![Selecting a green circuit recipe with uncommon quality](https://github.com/user-attachments/assets/306ae173-4bf9-4917-8ead-d7e364034651)

The recipe is properly set, as expected:
![A level 9 assembler working on a green circuit with uncommon quality](https://github.com/user-attachments/assets/20cac5c8-08f4-4b54-86e4-a70e5fb2992f)

Upon level up, the recipe is reset to "normal" quality:
![A now level 10 assembler working on a green circuit with normal quality](https://github.com/user-attachments/assets/236463ae-da77-499b-8e4e-06341e40b199)

# Expected behaviour

The factory upgrade should preserve the set quality of its recipe.

**Comment by ololduck** [comment]
It also seems that if a factory with a Quality (> "Normal") is upgraded, it will be with a "Normal" quality. Would you like me to open a separate issue for this?

**Comment by renoth** [comment]
no i will look into it

**Comment by renoth** [comment]
Please try 0.7.8

**Comment by ololduck** [comment]
I confirm that both the recipe quality reset and the assembler quality reset are functional.

An other issue quickly fixed! Thank you and well done!
