### ISSUE TITLE
Crashed probably with set recipe

### ISSUE THREAD

**Issue by xzanthar** [renoth/factorio-factory-levels#63]
What was going on -

was building an automated mini mall utilizing the set-recipe functionality,
I'm wondering if the error comes as it finishes the queue of what the circuits say to build (or possibly negative values)

ERROR:

The mod Factory Levels (0.7.6) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-levels::on_nth_tick(6)
Invalid ItemID: expected LuaItemPrototype, LuaItemStack, LuaItem or string.
stack traceback:
	[C]: in function 'insert'
	__factory-levels__/control.lua:347: in function 'insert_inventory_contents'
	__factory-levels__/control.lua:419: in function 'upgrade_factory'
	__factory-levels__/control.lua:449: in function 'replace_machines'
	__factory-levels__/control.lua:488: in function <__factory-levels__/control.lua:468>

**Comment by renoth** [comment]
Please try the latest version of this mod, it should be fixed

**Comment by xzanthar** [comment]
Thanks, it seems to have fixed the issue.

In other news, I also got around the issue by stopping my inserters on the "Read recipe finished" signal from the assembler
