### ISSUE TITLE
[Suggestion] Increase product quality only if the underlying machine has other quality-raising effects

### ISSUE THREAD

**Issue by MenzenEidos** [renoth/factorio-factory-levels#67]
Space Age: sadly, unconditional quality increase for products this mod also provides complicates a lot of production chains.
Now it is impossible to directly feed Machine A -> Machine B if the product has quality tiers.

Check this simple steel chain:
![qual_1](https://github.com/user-attachments/assets/6e120f9b-8a72-4269-84e7-752d1389aea4)

Once any Ore -> Iron furnace outputs a single [Uncommon] Iron plate, Steel Furnace either won't be able to accept it due to already having some [Normal] Iron plates inside waiting for 5th, or in case a Steel furnace was empty, it will accept a single [Uncommon] Iron plate, but next produced [Normal] plate won't be accepted, thus blocking the chain either way.

It can surely be solved by creating long output chains for every product (filter any quality above [Normal] for example), but the need to implement this filtering in ANY production chain with intermediate products seems to be a rather titanic task to do..

Hence, a suggestion:
- if an entity already has some product quality bonuses (quality modules, etc.), then also add the bonus this mod would provide to that producer
- otherwise, if the producer had no quality bonuses, do not add the bonus to quality from this mod to it

This way, the mod would still provide quality bonuses to some of the buildings, but not lead to any direct-feed clogging.

It is only a suggestion, as I'm not sure if this could be implemented in any reasonable way. But as of current mod version 0.7.8, many of my trusted blueprints have ceased to function, and I'm a bit overwhelmed by the need to circumvent it manually.

Thanks for your attention

**Comment by renoth** [comment]
I am sorry but the current modding API does not provide such finegrained control. This mod is already pushing the limits of what is possible without rewriting the core game.

**Comment by renoth** [comment]
No its impossible since effects is read only and determined by the prototype itself and the modules

**Comment by AlexFrest** [comment]
Joining the request  - to be able to disable the quality feature for factories/chems, etc w/o quality modules. 
Appearing the quality items on the belt - ruins the entire production chain (and in my case, the quality items appear at the beginning of the game).

**Comment by renoth** [comment]
As i said above: it is not possible, the modding API is too restricted.
