### ISSUE TITLE
Problemo

### ISSUE THREAD

**Issue by CarlosTorch** [renoth/factorio-factory-levels#69]
This takes section needs a fix. Would be great 
Thanks for your work.
![sshot-55](https://github.com/user-attachments/assets/6b6f0f74-cd90-4a3d-b92b-a4b679740f07)

**Comment by renoth** [comment]
Not possible without breaking upgrade planner.

**Comment by FluffyDiscord** [comment]
But we cannot see the item stats, this is in itself broken.

**Comment by renoth** [comment]
i dont care.
