### ISSUE TITLE
Accidentally building lower tier assembling machine crashes

### ISSUE THREAD

**Issue by CaitSith2** [renoth/factorio-factory-levels#7]
The issue I saw in the code that I had to be 100% sure would happen is that if an assembling machine 2 is level 26 or greater,  or an assembling machine level 3 is level 51 or greater, or a steel furnace is level 26 or greater when these are deconstructed for refactoring, and you accidentally build a lower tier machine,  then a crash happens because the level x of lower tier assembling machine or furnace don't exist.

The mod Factory Levels (0.2.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-levels::on_built_entity (ID 6)
Unknown entity name: assembling-machine-1-level-100
stack traceback:
	[C]: in function 'create_entity'
	__factory-levels__/control.lua:37: in function 'upgrade_factory'
	__factory-levels__/control.lua:154: in function <__factory-levels__/control.lua:144>

**Comment by renoth** [comment]
Thanks for reporting, should be fixed in 0.2.3
