### ISSUE TITLE
too much options for crafting

### ISSUE THREAD

**Issue by Lorrein34** [renoth/factorio-factory-levels#73]
![зображення_2024-10-30_001337352](https://github.com/user-attachments/assets/d724c7b6-05b0-4d89-861a-8485bfa28278)
cant see item descr cos of too much lavels of furnace

**Comment by renoth** [comment]
Yes there is a problem since 2.0, in 1.1 we could set the hidden flag that was removed. If i set the entity to hidden now the upgrade planner breaks. So this is the way it is at the moment since it is the lesser of two problems
