### ISSUE TITLE
disable quality setting as default

### ISSUE THREAD

**Issue by AsheX1** [renoth/factorio-factory-levels#75]
ya so i have bin having a problem where my factory comes to a complete halt as here or there some things made quality irons stick or plates and so on the problem these items clog up a belts and they cant be used it seems

quality irons plates was blocking cylinder engine line as the it does not use quality iron plates just normal iron plates 

i think its best to have this setting disabled by default as to not make quality items at random and clogging everything up

**Comment by AsheX1** [comment]
so if i look at this correct in settings.lua on line  57 
default_value = true
needs to become
default_value = false

**Comment by AsheX1** [comment]
its not big yet but allot of crap is not working anymore i need to check every belt to clear of quality items
![image](https://github.com/user-attachments/assets/bbd1a235-4bb7-48eb-afa6-ff16bba436f2)

**Comment by renoth** [comment]
So just turn off quality?
