### ISSUE TITLE
0.7.11 non-recoverable error

### ISSUE THREAD

**Issue by IG2WTC** [renoth/factorio-factory-levels#76]
Hi, thanks for trying to update for 2.0 buildings!

Seems there was a slight problem when loading a save and maybe this will help find the source:

The mod Factory Levels (0.7.11) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event factory-levels::on_configuration_changed
Unknown entity name: recycler-level-61
stack traceback:
	[C]: in function 'create_entity'
	__factory-levels__/control.lua:391: in function 'upgrade_factory'
	__factory-levels__/control.lua:434: in function 'replace_machines'
	__factory-levels__/control.lua:31: in function 'get_built_machines'
	__factory-levels__/control.lua:10: in function <__factory-levels__/control.lua:9>

**Comment by renoth** [comment]
Does the error still occur in 0.7.12?

**Comment by IG2WTC** [comment]
It seems to be fixed, nice work!
