### ISSUE TITLE
Excess input spilling

### ISSUE THREAD

**Issue by CaitSith2** [renoth/factorio-factory-levels#8]
If the assembling-machine or furnace is being filled by loaders, which WILL fill the machine to the max allowed, then the machine ends up spilling the excess on upgrade, and enough items are spilled to exceed the bounding box of the machine resulting in the spilled items not being deleted.

Also, it would be nice that if anything is spilled, it only deletes the item corresponding to the machine it just replaced.

![Items being spilled](https://i.imgur.com/37MIGLI.png)

As can be seen, enough items are spilled to result in the stone furnaces and steel furnaces to end up outside of the box where these would be deleted.

**Comment by renoth** [comment]
How does this happen? Do all entities inside assemblers get put on ground on replacing?

**Comment by CaitSith2** [comment]
Only seems to be the entities past the stack size of the ingredient.   Loaders, which are a native type to factorio will just feed the machine till it won't take any more,  while inserters specifically feed the machine for a limited quantity of ingredients, typically 10 of, or 2 crafts worth, whichever is greater.

**Comment by renoth** [comment]
Ive set spill to false, you can test if this fixes the problem

**Comment by CaitSith2** [comment]
This does indeed fix the problem.  No more free furnaces/assembling machines.

**Comment by renoth** [comment]
Thanks for reporting and testing! Released 0.2.5
